spring.application.name=weblearn
spring.mvc.apiversion.use.header=X-API-VERSION
logging.level.com.mysql.cj=DEBUG
logging.level.com.mysql.cj.jdbc=TRACE

spring.mvc.apiversion.use.path-segment=0
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework=info
management.endpoints.web.exposure.include=*
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:mysql://127.0.0.1:3307/cart_database?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=cart_user
#spring.datasource.password=mysqlpass

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# --- PostgreSQL connection settings ---
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/shopping_cart_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=buddham
spring.security.user.password=sharanam

#docker run --detach 
#--env MYSQL_ROOT_PASSWORD=rootpass 
#--env MYSQL_USER=cart_user 
#--env MYSQL_PASSWORD=mysqlpass 
#--env MYSQL_DATABASE=cart_database 
#--name cart 
#--publish 3307:3306 
#mysql:8-oracle